title: Mayukh Bhattacharyya
logo: /assets/img/dp.jpg
email: mayukhbhattacharyya18 at gmail.com
blank_title: true
favicon: true
description: ""
show_downloads: false
google_analytics: UA-108144808-1
remote_theme: BDHU/minimalist
color-scheme: auto
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-seo-tag

theme: jekyll-theme-minimal